#!/usr/bin/env node
/**
 * Script to discover all process.env.* usages and generate TypeScript declarations
 * Run: pnpm --filter @repo/env generate-env-types
 */

import { execSync } from "child_process";
import * as fs from "fs";
import * as path from "path";

const ROOT_DIR = path.resolve(__dirname, "../../..");
const OUTPUT_FILE = path.resolve(__dirname, "../env.d.ts");

// Patterns to search for
const ENV_PATTERN = /process\.env\.([A-Z][A-Z0-9_]*)/g;

// Known env vars with their types (add special cases here)
const KNOWN_TYPES: Record<string, string> = {
  NODE_ENV: '"development" | "production" | "test"',
  PORT: "string",
  HOST: "string",
};

function findEnvVars(): Set<string> {
  const envVars = new Set<string>();

  // Directories to scan (relative to ROOT_DIR)
  const SCAN_DIRS = ["apps", "packages"];
  const EXCLUDE_PATTERNS = ["node_modules", "dist", ".next", "build"];

  for (const dir of SCAN_DIRS) {
    const fullPath = path.join(ROOT_DIR, dir);
    if (!fs.existsSync(fullPath)) continue;

    try {
      // Use grep with --exclude-dir to skip node_modules
      const excludeArgs = EXCLUDE_PATTERNS.map(
        (p) => `--exclude-dir=${p}`,
      ).join(" ");
      const result = execSync(
        `grep -r ${excludeArgs} "process\\.env\\.[A-Z][A-Z0-9_]*" --include="*.ts" --include="*.tsx" -oh "${fullPath}" 2>/dev/null | sort -u`,
        { encoding: "utf-8", maxBuffer: 10 * 1024 * 1024 },
      ).trim();

      if (result) {
        for (const line of result.split("\n")) {
          const matches = line.matchAll(ENV_PATTERN);
          for (const match of matches) {
            if (match[1]) {
              envVars.add(match[1]);
            }
          }
        }
      }
    } catch {
      // grep returns error if no matches found, which is fine
    }
  }

  return envVars;
}

function generateDeclarationFile(envVars: Set<string>): string {
  const sortedVars = Array.from(envVars).sort();

  const declarations = sortedVars
    .map((varName) => {
      const type = KNOWN_TYPES[varName] || "string | undefined";
      return `    ${varName}?: ${type};`;
    })
    .join("\n");

  return `/**
 * Auto-generated environment variable type declarations
 * Generated by: pnpm --filter @repo/env generate-env-types
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated
 * To add new env vars, use them in the codebase and re-run the generator
 */

declare global {
  namespace NodeJS {
    interface ProcessEnv {
${declarations}
    }
  }
}

export {};
`;
}

function main() {
  console.log("🔍 Scanning for process.env.* usages...\n");

  const envVars = findEnvVars();

  if (envVars.size === 0) {
    console.log("No environment variables found.");
    return;
  }

  console.log(`Found ${envVars.size} environment variables:\n`);

  const sortedVars = Array.from(envVars).sort();
  for (const varName of sortedVars) {
    console.log(`  • ${varName}`);
  }

  const declaration = generateDeclarationFile(envVars);
  fs.writeFileSync(OUTPUT_FILE, declaration);

  console.log(`\n✅ Generated ${OUTPUT_FILE}`);
  console.log("\nMake sure to include this file in your tsconfig.json:");
  console.log('  "include": ["env.d.ts", ...]');
}

main();
