/**
 * Auto-generated environment variable type declarations
 * Generated by: pnpm --filter @repo/env generate-env-types
 *
 * DO NOT EDIT MANUALLY - This file is auto-generated
 * To add new env vars, use them in the codebase and re-run the generator
 */

declare global {
  namespace NodeJS {
    interface ProcessEnv {
      ADDITIONAL_TRUSTED_ORIGINS?: string | undefined;
      ADMIN_EMAILS?: string | undefined;
      API_PREFIX?: string | undefined;
      API_VERSION?: string | undefined;
      APPLE_APP_BUNDLE_IDENTIFIER?: string | undefined;
      APPLE_CLIENT_ID?: string | undefined;
      APPLE_CLIENT_SECRET?: string | undefined;
      AUTH_PROVIDERS?: string | undefined;
      AWS_LAMBDA_FUNCTION_NAME?: string | undefined;
      AWS_SES_ACCESS_KEY_ID?: string | undefined;
      AWS_SES_CONFIGURATION_SET_NAME?: string | undefined;
      AWS_SES_FROM_ARN?: string | undefined;
      AWS_SES_REGION?: string | undefined;
      AWS_SES_SECRET_ACCESS_KEY?: string | undefined;
      CF_PAGES?: string | undefined;
      CLOUDFLARE_WORKERS?: string | undefined;
      COOKIE_DOMAIN?: string | undefined;
      COOKIE_PREFIX?: string | undefined;
      CORS_ORIGIN?: string | undefined;
      DATABASE_DRIVER?: string | undefined;
      DATABASE_URL?: string | undefined;
      DB_CONNECTION_TIMEOUT?: string | undefined;
      DB_HOST?: string | undefined;
      DB_IDLE_TIMEOUT?: string | undefined;
      DB_NAME?: string | undefined;
      DB_PASSWORD?: string | undefined;
      DB_POOL_MAX?: string | undefined;
      DB_POOL_MIN?: string | undefined;
      DB_PORT?: string | undefined;
      DB_SSL?: string | undefined;
      DB_USER?: string | undefined;
      DEPLOYMENT_MODE?: string | undefined;
      DISABLE_SIGNUP?: string | undefined;
      EMAIL_FROM?: string | undefined;
      EMAIL_PROVIDER?: string | undefined;
      ENABLE_ADMIN_UI?: string | undefined;
      ENABLE_CROSS_SUBDOMAIN_COOKIES?: string | undefined;
      ENABLE_EMAIL_PASSWORD?: string | undefined;
      ENABLE_JWT?: string | undefined;
      ENABLE_MAGIC_LINK?: string | undefined;
      ENABLE_MULTI_SESSION?: string | undefined;
      ENABLE_ONE_TAP?: string | undefined;
      ENABLE_OTP?: string | undefined;
      ENABLE_QUEUE?: string | undefined;
      ENABLE_REDIS?: string | undefined;
      ENABLE_USERNAME?: string | undefined;
      ENABLE_WEBSOCKET?: string | undefined;
      FACEBOOK_CLIENT_ID?: string | undefined;
      FACEBOOK_CLIENT_SECRET?: string | undefined;
      FACEBOOK_REDIRECT_URI?: string | undefined;
      GOOGLE_CLIENT_ID?: string | undefined;
      GOOGLE_CLIENT_SECRET?: string | undefined;
      HEALTH_CHECK_INTERVAL?: string | undefined;
      HOST?: string;
      JWT_AUDIENCE?: string | undefined;
      JWT_ISSUER?: string | undefined;
      LOG_LEVEL?: string | undefined;
      LOG_PRETTY?: string | undefined;
      MAGIC_LINK_EXPIRY_MINUTES?: string | undefined;
      MAX_PASSWORD_LENGTH?: string | undefined;
      MAX_SESSIONS_PER_USER?: string | undefined;
      MIGRATION_DB?: string | undefined;
      MIN_PASSWORD_LENGTH?: string | undefined;
      NEXT_PUBLIC_API_URL?: string | undefined;
      NEXT_PUBLIC_FRONTEND_URL?: string | undefined;
      NEXT_PUBLIC_SERVICE_MODE?: string | undefined;
      NODE_ENV?: "development" | "production" | "test";
      NOTIFICATIONS_EMAIL_ENABLED?: string | undefined;
      NOTIFICATIONS_PUSH_ENABLED?: string | undefined;
      NOTIFICATIONS_SMS_ENABLED?: string | undefined;
      OTP_EXPIRY_MINUTES?: string | undefined;
      OTP_LENGTH?: string | undefined;
      OTP_MAX_ATTEMPTS?: string | undefined;
      PORT?: string;
      QUEUE_ARCHIVE_COMPLETED_HOURS?: string | undefined;
      QUEUE_DELETE_AFTER_DAYS?: string | undefined;
      QUEUE_MAINTENANCE_INTERVAL_MINUTES?: string | undefined;
      QUEUE_MAX_EXPIRY_HOURS?: string | undefined;
      QUEUE_RETRY_BACKOFF?: string | undefined;
      QUEUE_RETRY_DELAY?: string | undefined;
      QUEUE_RETRY_LIMIT?: string | undefined;
      QUEUE_SCHEMA?: string | undefined;
      R2_ACCESS_KEY_ID?: string | undefined;
      R2_ACCOUNT_ID?: string | undefined;
      R2_BUCKET_NAME?: string | undefined;
      R2_PUBLIC_URL?: string | undefined;
      R2_REGION?: string | undefined;
      R2_SECRET_ACCESS_KEY?: string | undefined;
      RAILWAY_PUBLIC_DOMAIN?: string | undefined;
      RATE_LIMIT_MAX?: string | undefined;
      RATE_LIMIT_WINDOW?: string | undefined;
      REDIS_DB?: string | undefined;
      REDIS_HOST?: string | undefined;
      REDIS_PASSWORD?: string | undefined;
      REDIS_PORT?: string | undefined;
      REDIS_URL?: string | undefined;
      REDIS_USERNAME?: string | undefined;
      RENDER_EXTERNAL_URL?: string | undefined;
      RESEND_KEY?: string | undefined;
      TRUSTED_ORIGINS?: string | undefined;
      VERCEL?: string | undefined;
      VERCEL_URL?: string | undefined;
    }
  }
}

export {};
