// THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY.
// Run the generation script to regenerate.

export interface Welcome {}

export interface Common {
  error: string;
}

export interface Resources {
  welcome: Welcome;
  common: Common;
}

export type WelcomeKeys = {};
export type CommonKeys = "error";

export type TranslationKeys = "common.error";

export type DefaultNamespace = keyof Resources;
